#if TIDE_TEST_FRAMEWORK
using System;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Newtonsoft.Json.Linq;
using NUnit.Framework;
using Tide.App;
using Tide.Save;
using Tide.Sim;
using UnityEngine;
namespace Tide.Tests {
 public sealed class T0M2Tests {
  T0Definition data;T0Simulation sim;string directory;
  static void RunAsync(Func<Task> body){var task=Task.Run(body);if(!task.Wait(TimeSpan.FromSeconds(20)))throw new TimeoutException("Save test exceeded 20 seconds");task.GetAwaiter().GetResult();}
  [SetUp] public void SetUp(){data=Resources.Load<T0RuntimeConfig>("T0Runtime").catalog.Load();sim=new T0Simulation(data);directory=Path.Combine(Path.GetTempPath(),"t0-m2-test-"+Guid.NewGuid().ToString("N"));}
  [TearDown] public void TearDown(){if(Directory.Exists(directory))Directory.Delete(directory,true);}
  CommandJournal Journal(){var j=new CommandJournal(sim);foreach(var r in data.Beats[0].Requirements){foreach(var id in r.Ids){if(r.Type=="recordLinesViewed")Do(j,new PuzzleCommand("ViewLine",r.RecordId,id));if(r.Type=="recordRowsViewed")Do(j,new PuzzleCommand("ViewRow",r.RecordId,id));}if(r.Type=="slotLoaded")Do(j,new PuzzleCommand("PlaceInSlot",r.Id,r.RecordId));if(r.Type=="decisionRecorded")Do(j,new PuzzleCommand("RecordDecision",r.Id,r.Ids[0]));}return j;}
  static void Do(CommandJournal j,PuzzleCommand c){var v=j.Submit(c);Assert.IsTrue(v.IsValid,v.DataDiagnostic??v.Reason?.ToString());}
  void Circuit(CommandJournal j){Do(j,new PuzzleCommand("OpenTool","circuit"));Do(j,new PuzzleCommand("TraceSystem",data.SystemIds[0]));Do(j,new PuzzleCommand("BeginOverlay"));Do(j,new PuzzleCommand("SetOverlayOffset",value:"-1",otherValue:"1"));Do(j,new PuzzleCommand("AnchorOverlay"));foreach(var area in data.UncoveredAreas){Do(j,new PuzzleCommand("ToggleUncovered",area));Do(j,new PuzzleCommand("AttachAreaEvidence",area,"rec-watchlog-bureau"));}}
  JObject Encode(CommandJournal j,string key="key",int cap=20000)=>JournalSave.Encode(j,key,cap,6291456);
  [Test] public void RedoFollowsSelectedBranchAcrossSharedAncestors(){var j=Journal();Do(j,new PuzzleCommand("LoadRecord","rec-handover-brief"));var b=j.HeadSeq;Do(j,new PuzzleCommand("LoadRecord","rec-transfer-list"));j.Undo();Do(j,new PuzzleCommand("LoadRecord","rec-handover-brief"));var d=j.HeadSeq;j.Undo();j.Undo();Assert.IsTrue(j.Redo());Assert.AreEqual(b,j.HeadSeq);Assert.IsTrue(j.Redo());Assert.AreEqual(d,j.HeadSeq);}
  [Test] public void UnknownVersionsRefuseEvenWithValidBackup(){RunAsync(async()=>{var store=new AtomicSaveStore(directory);await store.WriteAsync(Encode(Journal(),"base"));foreach(var token in new JToken[]{JValue.CreateNull(),new JValue(-1),new JValue(1.5),new JValue("1")}){await store.WriteAsync(Encode(Journal(),Guid.NewGuid().ToString()));var doc=Encode(Journal(),Guid.NewGuid().ToString());doc["schemaVersion"]=token;await store.WriteAsync(doc);var raw=File.ReadAllText(Path.Combine(directory,"save.json"));Assert.AreEqual(2,(int)SaveCodec.Decode(File.ReadAllText(Path.Combine(directory,"save.bak")))["schemaVersion"]);Assert.AreEqual("SAVE_VERSION_REFUSED",store.Load().Failure);Assert.AreEqual(raw,File.ReadAllText(Path.Combine(directory,"save.json")));}});}
  [Test] public void CircuitFsmRejectsBypassAndBadOffsets(){var j=Journal();Assert.IsFalse(j.Submit(new PuzzleCommand("ToggleUncovered",data.UncoveredAreas[0])).IsValid);Do(j,new PuzzleCommand("OpenTool","circuit"));Assert.AreEqual("Tracing",sim.CircuitMode(j.State));Do(j,new PuzzleCommand("BeginOverlay"));Assert.IsFalse(j.Submit(new PuzzleCommand("SetOverlayOffset",value:"NaN",otherValue:"0")).IsValid);Assert.IsFalse(j.Submit(new PuzzleCommand("AnchorOverlay")).IsValid);Do(j,new PuzzleCommand("SetOverlayOffset",value:"-1",otherValue:"1"));Do(j,new PuzzleCommand("AnchorOverlay"));Assert.AreEqual("Marking",sim.CircuitMode(j.State));}
  [Test] public void CircuitCancelCloseAndReopenPreserveUnrelatedState(){var j=Journal();var intake=j.State.StateHash;Do(j,new PuzzleCommand("OpenTool","circuit"));Do(j,new PuzzleCommand("BeginOverlay"));Do(j,new PuzzleCommand("SetOverlayOffset",value:"1000000",otherValue:"-1000000"));Do(j,new PuzzleCommand("Cancel"));Assert.AreEqual("Tracing",sim.CircuitMode(j.State));Assert.IsNull(j.State.Get("overlayX"));Assert.IsTrue(sim.IsComplete(j.State,"t0-b1"));Do(j,new PuzzleCommand("CloseTool","circuit"));Assert.AreEqual("Idle",sim.CircuitMode(j.State));}
  [Test] public void FullCanonicalT0CompletesWithOneMediumPerAreaAndIndependentPair(){var j=Journal();Circuit(j);Assert.AreEqual("Resolved",sim.CircuitMode(j.State));Assert.IsTrue(sim.IsComplete(j.State,"t0-b2"));foreach(var id in new[]{"rec-plate-standard-hub","rec-tide-ledger-bureau"}){Do(j,new PuzzleCommand("LoadRecord",id));Do(j,new PuzzleCommand("Read"));Do(j,new PuzzleCommand("SetWindow",value:"H-1:00",otherValue:"H+3:00"));Do(j,new PuzzleCommand("CiteToBoard",id));}Assert.IsTrue(sim.IsComplete(j.State,"t0-b3"));var recovered=JournalSave.Decode(Encode(j),sim);Assert.AreEqual(j.State.StateHash,recovered.State.StateHash);Assert.AreEqual(0,recovered.State.ReadCount("rec-plate-standard-hub"));}
  [Test] public void ApprovedLedgerNullSystemIsValidAndOtherRecordsStayUnassigned(){Assert.IsTrue(data.Records["rec-tide-ledger-bureau"].HasCitationProvenance);Assert.IsNull(data.Records["rec-tide-ledger-bureau"].SystemId);Assert.AreEqual("system-hub",data.Records["rec-plate-standard-hub"].SystemId);Assert.IsNull(data.Records["rec-handover-brief"].StationId);Assert.IsNull(data.Overlay.FineGridStep);}
  [Test] public void JournalUndoRedoBranchesAndAutoCopiesAreImmutable(){var j=Journal();Circuit(j);Do(j,new PuzzleCommand("LoadRecord","rec-plate-standard-hub"));Do(j,new PuzzleCommand("Read"));var old=j.State;var clues=j.State.AutoKeptClues.ToArray();Assert.IsTrue(j.Undo());Assert.IsTrue(clues.All(j.State.AutoKeptClues.Contains));Assert.IsTrue(j.Redo());Do(j,new PuzzleCommand("ReadOriginal"));Assert.AreEqual(1,j.State.ReadCount("rec-plate-standard-hub"));Assert.AreEqual(0,old.ReadCount("rec-plate-standard-hub"));j.Undo();Do(j,new PuzzleCommand("SetWindow",value:"H-1:00",otherValue:"H+3:00"));Assert.AreNotEqual("main",j.BranchId);Assert.IsFalse(j.Redo());Assert.AreEqual(j.State.StateHash,JournalSave.Decode(Encode(j),sim).State.StateHash);}
  [Test] public void Snapshot200AndFoldKeepCurrentStateAndCoarseUndo(){var j=Journal();for(int i=0;i<220;i++)Do(j,new PuzzleCommand("LoadRecord","rec-handover-brief"));Assert.IsTrue(j.Snapshots.Any(s=>s.Seq==200));var before=j.State.StateHash;var doc=Encode(j,cap:20);Assert.LessOrEqual(((JArray)doc["commandLog"]["entries"]).Count,20);var restored=JournalSave.Decode(doc,sim);Assert.AreEqual(before,restored.State.StateHash);Assert.IsTrue(restored.CoarseUndo);int count=0;while(restored.Undo())Assert.Less(++count,100);Assert.AreEqual(0,restored.HeadSeq);Assert.IsTrue(restored.Redo());}
  [Test] public void SnapshotAndPayloadCorruptionReject(){var j=Journal();for(int i=0;i<201;i++)Do(j,new PuzzleCommand("LoadRecord","rec-handover-brief"));var doc=Encode(j);doc["commandLog"]["snapshots"][0]["stateHash"]="bad";Assert.Throws<InvalidOperationException>(()=>JournalSave.Decode(doc,sim));doc=Encode(j);doc["commandLog"]["entries"][0]["payload"]["value"]="bad";Assert.Throws<InvalidOperationException>(()=>JournalSave.Decode(doc,sim));}
  [Test] public void CanonicalSaveRootAndChecksumAreOrderIndependent(){var doc=Encode(Journal());Assert.IsTrue(Guid.TryParse((string)doc["saveId"],out _));Assert.IsNotNull(doc["createdUtc"]);Assert.IsNotNull(doc["progress"]);Assert.AreEqual((string)doc["createdUtc"],(string)SaveCodec.Decode(SaveCodec.Encode(doc))["createdUtc"]);Assert.IsNull(doc["stateHash"]);var reordered=new JObject(doc.Properties().Reverse().Select(p=>new JProperty(p.Name,p.Value.DeepClone())));Assert.AreEqual(SaveCodec.Encode(doc),SaveCodec.Encode(reordered));Assert.Throws<InvalidOperationException>(()=>SaveCodec.Decode(SaveCodec.Encode(doc).Replace("21:00","22:00")));}
  [TestCase(SaveStage.BeforeWrite)] [TestCase(SaveStage.DuringWrite)] [TestCase(SaveStage.BeforeRename)]
  public void InterruptedWritePreservesPreviousSave(SaveStage stage){RunAsync(async()=>{var store=new AtomicSaveStore(directory);var before=Encode(Journal(),"before");await store.WriteAsync(before);store.Injection=(s,t)=>s==stage?Task.FromException(new IOException("injected")):Task.CompletedTask;Assert.ThrowsAsync<IOException>(async()=>await store.WriteAsync(Encode(Journal(),"after")));Assert.AreEqual("before",(string)store.Load().Document["commitIdempotencyKey"]);Assert.IsFalse(File.Exists(Path.Combine(directory,"save.json.tmp")));});}
  [Test] public void AfterRenameRetryIsIdempotent(){RunAsync(async()=>{var store=new AtomicSaveStore(directory);var doc=Encode(Journal());store.Injection=(s,t)=>s==SaveStage.AfterRename?Task.FromException(new IOException("after rename")):Task.CompletedTask;Assert.ThrowsAsync<IOException>(async()=>await store.WriteAsync(doc));store.Injection=null;Assert.IsFalse(await store.WriteAsync(doc));Assert.AreEqual("key",(string)store.Load().Document["commitIdempotencyKey"]);});}
  [Test] public void CancellationBeforeRenameDoesNotPublish(){RunAsync(async()=>{var store=new AtomicSaveStore(directory);var cancel=new CancellationTokenSource();store.Injection=(s,t)=>{if(s==SaveStage.BeforeRename)cancel.Cancel();return Task.CompletedTask;};Assert.CatchAsync<OperationCanceledException>(async()=>await store.WriteAsync(Encode(Journal()),cancellation:cancel.Token));Assert.AreEqual("empty",store.Load().Source);});}
  [Test] public void TruncationRecoversBackupThenCheckpointWithoutDeletingBytes(){RunAsync(async()=>{var store=new AtomicSaveStore(directory);await store.WriteAsync(Encode(Journal(),"old"));await store.WriteAsync(Encode(Journal(),"new"));File.WriteAllText(Path.Combine(directory,"save.json"),"{");Assert.AreEqual("save.bak",store.Load(validate:d=>JournalSave.Decode(d,sim)).Source);await store.WriteAsync(Encode(Journal(),"checkpoint"),"checkpoint.pre-commit.json");File.WriteAllText(Path.Combine(directory,"save.bak"),"bad");Assert.AreEqual("checkpoint.pre-commit.json",store.Load().Source);Assert.AreEqual("{",File.ReadAllText(Path.Combine(directory,"save.json")));});}
  [Test] public void VersionZeroMigratesWithBackupAndFutureVersionIsRefused(){RunAsync(async()=>{var store=new AtomicSaveStore(directory);var doc=Encode(Journal());doc["schemaVersion"]=0;await store.WriteAsync(doc);var loaded=store.Load();Assert.IsTrue(loaded.Migrated);Assert.IsTrue(File.Exists(Path.Combine(directory,"save.json.v0.bak")));doc["schemaVersion"]=3;doc["commitIdempotencyKey"]="future";await store.WriteAsync(doc);var bytes=File.ReadAllBytes(Path.Combine(directory,"save.json"));Assert.AreEqual("SAVE_VERSION_REFUSED",store.Load().Failure);CollectionAssert.AreEqual(bytes,File.ReadAllBytes(Path.Combine(directory,"save.json")));});}
 }
}
#endif
