using System;
using System.Collections.Generic;
using Tide.Sim;
using UnityEngine;

namespace Tide.Data
{
    // Holds the exact generated bytes and producer receipt; runtime authoring remains read-only.
    public sealed class T0CatalogAsset : ScriptableObject
    {
        [SerializeField] private TextAsset[] tables;
        [SerializeField] private TextAsset receipt;
        [SerializeField,TextArea] private string producerReceipt;
        public void Configure(TextAsset[] source,TextAsset receiptAsset)
        {
#if UNITY_EDITOR
            tables=(TextAsset[])source.Clone(); receipt=receiptAsset; producerReceipt=receiptAsset.text;
#else
            throw new InvalidOperationException("Authoring is editor-only");
#endif
        }
        public T0Definition Load()
        {
            var files=new Dictionary<string,byte[]>(StringComparer.Ordinal);
            foreach(var table in tables) files.Add(table.name+".json",table.bytes);
            return T0DataLoader.LoadVerified(files,receipt.bytes,System.Text.Encoding.UTF8.GetBytes(producerReceipt));
        }
    }
}

